[generator:features] Speedup features generation: reuse vector's
mapsme/geocore pull request #55
Opened 2019-11-22 15:50 UTC by cc-engineering

Минимизация расхода памяти.

При генерации фич из o5m файла, сами фичи формируются в пуле тредов чтения o5m файла, а записываются один тредом-писателем. Читатели выделяют память для каждой фичи и передают их треду-писателю через очередь. Получается, что память выделяется в нескольких тредах, а освобождается только в одном. Освобождённая память возвр. в общий пул, только при достижении опред. порога, но этот порог слишком высок для нас (в случае tcmalloc) т.к. в процесс ещё отображено порядка 180 GB данных из файлов (o5m, nodes, ways, relations) и буфера файлов частично вытесняются.

Тек. PR минимизирует аллокации векторов под фич, и освобождение памяти происх. в том же треде, что и аллокация.

2019-11-25 09:54 UTC, LaGrunge commented on generator/feature_processing_layers.hpp
> +    m_queuBuffers.push_back(m_buffer);
Странное название

2019-11-25 10:02 UTC, LaGrunge commented on generator/feature_processing_layers.hpp
> +    auto & data = (*m_buffer)[m_bufferSize];
Что это блин?

2019-11-25 10:09 UTC, LaGrunge commented
В целом здорово, что есть такие классные идеи, плохо то, что если раньше код читался как анекдот, теперь это уже Хайдеггер не меньше, а все же знают, что читать важнее, чем писать.

2019-11-25 11:03 UTC, LaGrunge requested changes
Я прошу пощады

2019-11-25 12:05 UTC, cc-engineering commented on generator/feature_processing_layers.hpp
> +    m_queuBuffers.push_back(m_buffer);
m_queuBuffers -> m_queuedChunks

2019-11-25 12:05 UTC, cc-engineering commented on generator/feature_processing_layers.hpp
> +    auto & data = (*m_buffer)[m_bufferSize];
переименовал

2019-11-25 14:40 UTC, LaGrunge approved these changes

2019-11-25 15:31 UTC, syershov commented on generator/feature_processing_layers.hpp
> +  ProcessedData & PlaceNewFeatureInBuffer()
Перенеси перед определением переменных, они идут последними в описании класса.

2019-11-26 12:51 UTC, syershov approved these changes

2019-11-26 12:53 UTC, syershov commented on generator/feature_processing_layers.hpp
> +  ProcessedData & PlaceNewItemInBuffer()
Определение полей класса должно быть после определения всех методов.

2019-11-27 12:24 UTC, cc-engineering commented on generator/feature_processing_layers.hpp
> +  ProcessedData & PlaceNewItemInBuffer()
++

2019-11-27 12:24 UTC, cc-engineering commented on generator/feature_processing_layers.hpp
> +  ProcessedData & PlaceNewFeatureInBuffer()
++

2019-11-27 12:32 UTC, syershov approved these changes

2019-11-27 12:32 UTC, merged